// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/gladinov/effective_mobile_test_assignment/internal/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, sub
func (_m *Storage) Create(ctx context.Context, sub domain.Subscription) (uuid.UUID, error) {
	ret := _m.Called(ctx, sub)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Subscription) (uuid.UUID, error)); ok {
		return rf(ctx, sub)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Subscription) uuid.UUID); ok {
		r0 = rf(ctx, sub)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Subscription) error); ok {
		r1 = rf(ctx, sub)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteByID provides a mock function with given fields: ctx, subID
func (_m *Storage) DeleteByID(ctx context.Context, subID uuid.UUID) error {
	ret := _m.Called(ctx, subID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, subID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: ctx, subID
func (_m *Storage) GetByID(ctx context.Context, subID uuid.UUID) (domain.Subscription, error) {
	ret := _m.Called(ctx, subID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 domain.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.Subscription, error)); ok {
		return rf(ctx, subID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.Subscription); ok {
		r0 = rf(ctx, subID)
	} else {
		r0 = ret.Get(0).(domain.Subscription)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, subID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTotal provides a mock function with given fields: ctx, filter, currentMonth
func (_m *Storage) GetTotal(ctx context.Context, filter domain.FilterTotal, currentMonth domain.YearMonth) (int64, error) {
	ret := _m.Called(ctx, filter, currentMonth)

	if len(ret) == 0 {
		panic("no return value specified for GetTotal")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.FilterTotal, domain.YearMonth) (int64, error)); ok {
		return rf(ctx, filter, currentMonth)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.FilterTotal, domain.YearMonth) int64); ok {
		r0 = rf(ctx, filter, currentMonth)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.FilterTotal, domain.YearMonth) error); ok {
		r1 = rf(ctx, filter, currentMonth)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, pagination
func (_m *Storage) List(ctx context.Context, pagination domain.Pagination) ([]domain.Subscription, error) {
	ret := _m.Called(ctx, pagination)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Pagination) ([]domain.Subscription, error)); ok {
		return rf(ctx, pagination)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Pagination) []domain.Subscription); ok {
		r0 = rf(ctx, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Pagination) error); ok {
		r1 = rf(ctx, pagination)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateByID provides a mock function with given fields: ctx, subID, sub
func (_m *Storage) UpdateByID(ctx context.Context, subID uuid.UUID, sub domain.Subscription) error {
	ret := _m.Called(ctx, subID, sub)

	if len(ret) == 0 {
		panic("no return value specified for UpdateByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, domain.Subscription) error); ok {
		r0 = rf(ctx, subID, sub)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdatePartialByID provides a mock function with given fields: ctx, subID, update
func (_m *Storage) UpdatePartialByID(ctx context.Context, subID uuid.UUID, update domain.SubscriptionUpdate) error {
	ret := _m.Called(ctx, subID, update)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePartialByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, domain.SubscriptionUpdate) error); ok {
		r0 = rf(ctx, subID, update)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewStorage creates a new instance of Storage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *Storage {
	mock := &Storage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
